"""auto migration

Revision ID: 99393a434253
Revises: c6fa46cde1da
Create Date: 2026-01-27 21:59:29.457670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99393a434253'
down_revision = 'c6fa46cde1da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
