"""auto_migration_20260127_221047

Revision ID: b95f58d947a8
Revises: 9ecf7d65f9a0
Create Date: 2026-01-27 22:10:47.689850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95f58d947a8'
down_revision = '9ecf7d65f9a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
