"""auto_migration_20260127_221117

Revision ID: 36f4594032ab
Revises: b95f58d947a8
Create Date: 2026-01-27 22:11:18.313559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f4594032ab'
down_revision = 'b95f58d947a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
