"""auto_migration_20260127_221020

Revision ID: 9ecf7d65f9a0
Revises: dec3d95a0091
Create Date: 2026-01-27 22:10:20.707764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecf7d65f9a0'
down_revision = 'dec3d95a0091'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
